Friendship milestone5
ricardomonte/ror-social-scaffold pull request #2
Opened 2020-12-01 22:19 UTC by chubaquelo

In this milestone we implemented the following features:
- Friendship mutual associations.
- Send Friend request feature in views.
- Confirm the Friend request feature in views.
- Add custom methods to the User model.
- Rspec tests for models and features using Capybara.

2020-12-01 22:57 UTC, Spayco requested changes
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] please enable GitHub Actions (use [this](https://github.com/microverseinc/linters-config/tree/master/ror))

- [x] make sure you cover both positive (.to be) and negative (.not_to be) scenarios in your testings ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [ ] when I (user_1) send a friend request to another user (user_2), it doesn't show up on user_2's end, but I still see a button for sending a friend request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**_when you fix that issue, make sure these work as well 👇 (since I can't check them while this issue is occurring)_**

- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))





### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-12-02 19:04 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

- All the project features are working. Great job!

- Your tests are amazing! I have seen very few students who write such extensive tests. Keep up with this momentum!

### However, we need to work on some changes before we can merge.

- I only found just one issue with your tests. You are using more than one `expect` statement in ALL the **feature test** scenarios. 

  - [ ] Please separate the tests so that each test will only have one `expect` statement.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-12-02 19:04 UTC, tirthajyoti-ghosh commented on spec/features/create_comment_spec.rb
> +    expect(page).to have_content('Johnny Bravo: This is a new comment for testing.')
Please use only one `expect` statement per test. If you have multiple expect statements, then break down the tests. You can use `before_each` to avoid repeating `visit`, `fill_in`, and `click_on` statements.

**IMPORTANT!** Please note that this is just one place where I am pointing this out. Please go through all your **feature** tests and separate the `expect` statements.

2020-12-02 20:28 UTC, chubaquelo commented on spec/features/create_comment_spec.rb
> +    expect(page).to have_content('Johnny Bravo: This is a new comment for testing.')
We did add before(:example) for each features testing for simpler code, thanks for the advice!

2020-12-02 20:38 UTC, blackpintz approved these changes
# Status: Approved 🎉 

**Hello team 😄. Congratulations. But before you merge, in your readme run test manual, you have misspelt `rspec`. Please correct that. Otherwise, I wish you luck in your next milestone 😎.**

2020-12-02 20:50 UTC, merged